services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: g_scores
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis:bookworm
    container_name: redis_g_scores
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
